### Tensor: 


In [2]:
from __future__ import print_function
import torch

Nếu "import torch" hiện lỗi 

    ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

thì bạn mở terminal và gõ: ``conda install -c anaconda cudatoolkit==9.0``

tạo ma trận ngẫu nhiện cỡ $2\times 3$:

In [5]:
x = torch.rand(2, 3)
print(x)

tensor([[0.0345, 0.1157, 0.5624],
        [0.9215, 0.8910, 0.4010]])


Tạo ma trận với các phần tử đều bằng 0 và có định dạng dtype long:



In [6]:
x = torch.zeros(2, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0]])


Tạo tensor trực tiếp từ dữ liệu:


In [15]:
# từ list trong python
x = torch.tensor([5,6, 3.3])
print(x)

tensor([5.0000, 6.0000, 3.3000])


In [14]:
ten = torch.IntTensor([[1, 2],[3, 4]])
print(ten)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [17]:
# từ numpy array
import numpy as np
v = np.array([5, 6,7])
t4 = torch.Tensor(v)
print(t4)

tensor([5., 6., 7.])


In [18]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [19]:
torch.arange(0, 5)

tensor([0, 1, 2, 3, 4])

Tạo tensor mới bằng cách chỉnh sửa tensor hiện có:

In [8]:
# Dựa trên kích cỡ, thông qua new_*
x = x.new_ones(2, 3, dtype=torch.double)      
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
# đổi kiểu tensor cũ từ double --> float; từ toàn 1 sang ngẫu nhiên (qua randn_like)
# giữ nguyên kích oc74 cũng tensor
x = torch.randn_like(x, dtype=torch.float)     
print(x)                                      

tensor([[-0.3145,  0.4801,  1.8691],
        [ 0.5322, -0.8327,  1.0082]])


tìm kích cỡ:

In [10]:
print(x.size())

torch.Size([2, 3])


tìm gía trị tại ví trí (1,2) của tensor:

In [12]:
x[1][2]

tensor(1.0082)

Gán giá trị mới 

In [13]:
x[1][2] = 5
x

tensor([[-0.3145,  0.4801,  1.8691],
        [ 0.5322, -0.8327,  5.0000]])

# Syntax:

In [16]:
x

tensor([[-1.4789,  0.5013,  0.0608],
        [ 1.6432,  1.7895, -0.2383],
        [ 0.0701,  1.3121, -1.1659],
        [-2.4942, -0.2412, -0.7019],
        [ 0.5301, -0.1938, -0.0372]])

In [18]:
y = torch.rand(5, 3)
# phép cộng
print(x + y)

tensor([[-0.7497,  1.3594,  0.1843],
        [ 1.8557,  2.0251,  0.6177],
        [ 0.5906,  2.2285, -0.1787],
        [-1.7562,  0.4727,  0.2574],
        [ 0.5987,  0.0068,  0.5912]])


hoặc 

In [19]:
print(torch.add(x, y))

tensor([[-0.7497,  1.3594,  0.1843],
        [ 1.8557,  2.0251,  0.6177],
        [ 0.5906,  2.2285, -0.1787],
        [-1.7562,  0.4727,  0.2574],
        [ 0.5987,  0.0068,  0.5912]])


cách khác:

In [20]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.7497,  1.3594,  0.1843],
        [ 1.8557,  2.0251,  0.6177],
        [ 0.5906,  2.2285, -0.1787],
        [-1.7562,  0.4727,  0.2574],
        [ 0.5987,  0.0068,  0.5912]])


cách khác nữa:

In [21]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.7497,  1.3594,  0.1843],
        [ 1.8557,  2.0251,  0.6177],
        [ 0.5906,  2.2285, -0.1787],
        [-1.7562,  0.4727,  0.2574],
        [ 0.5987,  0.0068,  0.5912]])


<div class="alert alert-info"><h4>Note</h4><p> những phép toán biến đổi tensor tại chỗ với đuôi  ``_``.
    chẳng hạn: ``x.copy_(y)``, ``x.t_()``, sẽ thay đổi  ``x``.</p></div>


Phép nhân tensor:

In [20]:
a = torch.rand((2, 3))
b = torch.rand((3, 2))

torch.mm(a, b)

tensor([[0.9158, 0.8164],
        [0.4039, 0.5113]])

# Index:
tương tự trong numpy

In [23]:
print(x[:, 1])

tensor([ 0.5013,  1.7895,  1.3121, -0.2412, -0.1938])


đổi kích cỡ tensor bằng ``torch.view``:



In [25]:
x = torch.randn(2, 2)
x

tensor([[-1.1285, -1.9510],
        [-3.4347,  0.0557]])

In [26]:
y = x.view(4)
y

tensor([-1.1285, -1.9510, -3.4347,  0.0557])

In [28]:
z = x.view(-1, 4)  # the size -1 is inferred from other dimensions
z

tensor([[-1.1285, -1.9510, -3.4347,  0.0557]])

**đọc thêm:**

các phép toán trên tensor, index, cắt,...:

  `here <http://pytorch.org/docs/torch>`_.

Pytorch và NumPy:
------------

chuyển một Tensor trong Torch sang một NumPy Array:


In [33]:
a = torch.ones(3)
print(a)

tensor([1., 1., 1.])


In [34]:
b = a.numpy()
print(b)

[1. 1. 1.]


**chú ý:** trong ví dụ sau, ta chỉ cộng trên a nhưng các giá trị của b cũng bị thay đổi 

In [35]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2.])
[2. 2. 2.]


Chuyển từ NumPy Array sang Torch Tensor thì chuyện tương tự cũng xảy ra:

In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
